# sync stub for cloud environment (publish_article.py insertion target)
SYNC_FILES = [
    "guide-signal-lab-026.html",
    "guide-signal-lab-027.html",
    "guide-proverb-ochiru-knife.html",
    "guide-news-2026-07-02-nikkei-kioxia-ai-selloff.html",
    "guide-signal-lab-028.html",
    "guide-proverb-tamago-kago.html",
    "guide-news-2026-07-03-nfp-june-2026.html",
    "guide-signal-lab-029.html",
    "guide-proverb-uwasa-jijitsu.html",
    "guide-signal-lab-030.html",
    "guide-proverb-hito-no-iku-ura.html",
    "guide-news-2026-07-05-tariff-august-deadline.html",
    "guide-bonds-interest-rates.html",
    "guide-signal-lab-031.html",
    "guide-simple-vs-compound.html",
    "guide-proverb-mikiri-senryo.html",
    "guide-signal-lab-032.html",
    "guide-proverb-mou-mada.html",
    "guide-news-2026-07-07-samsung-nikkei-selloff.html",
    "guide-signal-lab-033.html",
    "guide-proverb-soba-ni-kike.html",
    "guide-news-2026-07-08-fomc-minutes-warsh.html",
]
